<?php
header("Location: https://www.google.com/search?sxsrf=ALeKk00HIwDP11PJIG3Dzw4INGrjVEEeag%3A1589956998335&ei=htHEXsz6E8WpmgfHl6WADQ&q=Norton+product+setup&oq=Norton+product+setup&gs_lcp=CgZwc3ktYWIQAzIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIICAAQFhAKEB4yBggAEBYQHjoECAAQRzoECAAQQzoCCAA6BAgAEAo6BQgAEJECUKKvAliZ3QJgpd8CaAFwAXgAgAH1A4gBxjySAQY0LTE2LjGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjM1d-w68HpAhXFlOYKHcdLCdAQ4dUDCAs&uact=5");
die();
?>
